### ISSUE TITLE
error string in array not throw error

### ISSUE THREAD

**Issue by akecn** [humanwhocodes/momoa#10]
**Tell us about your environment**

* **Momoa Version:** 2.0.0
* **Node Version:** 15.5.0
* **npm Version:** 7.3.0

**Which function(s) is causing a problem?**

[ ] `interpret()`
[ ] `iterator()`
[x] `parse()`
[ ] `print()`
[ ] `traverse()`
[ ] `tokenize()`

**Example JSON code that demonstrates the problem:**

```json
// error string
{
  "key": [1, 2, {"key: 1}]
}
```

**What did you do?**
if not in array, will throw error quickly. but in array not throw error

```js
const momoa = require('@humanwhocodes/momoa');

const ast = momoa.parse(`{
  "key": [1, 2, {"key: 1}]
}`);

console.log(ast);
```

**What did you expect to happen?**
throw error

**What actually happened?**
process hung, and not return

**What do you think the solution is?**
maybe endless loop cause this when parse

**Comment by nzakas** [comment]
Thanks, I’ll take a look.
