### ISSUE TITLE
Feature request: parse YAML as Momoa AST

### ISSUE THREAD

**Issue by drwpow** [humanwhocodes/momoa#119]
This is a bit of a weird request, but I’m using Momoa in a tool that can handle both YAML and JSON. JSON is a “first-class” citizen, while YAML is secondary, and for that reason I’ve built the core engine on Momoa (also because I didn’t find any YAML AST libraries I liked).

However, for simplicity, to add back YAML support, I was planning on building a parser that takes YAML and spits out a Momoa AST that maps back to the original source file. For starters, I was planning on the following:

- **Only support JSON-like parts of YAML.** This fundamentally isn’t a full-fledged YAML parsing engine. It won’t support things like references, and YAML’s extensions to JSON. This is still a JSON AST that can just handle basic YAML.
- **Not supporting Rust.** This is just a Node.js/JS API. I don’t have Rust packages where I need this.
- **Limiting to the Momoa AST.** This isn’t a comprehensive YAML → JSON converter, nor a CLI, nor anything in that category. This only spits out a Momoa AST from a YAML file, using JS, and that’s it.

So all that to say, I had the following questions for you:

1. Is this a project you’d be interested in joining in (have you ever had this need? no worries if not)?
2. Do you have any preference on what the npm package should be called (e.g. `yaml-to-momoa-ast`)?
3. Are there any other requests you have before starting on this project? You’d be credited for Momoa and all Momoa-related things of course, but let me know if there are any considerations I need to make (like avoiding mentioning the famous actor, etc.).

Thanks for a great project!

**Comment by nzakas** [comment]
Thanks for the note. I've actually considered adding some YAML support into Momoa, but likely won't have the time to do so in the near future. I think the Momoa AST should work well for this purpose if you stick to JSON-like values.

No requests on my part. Open source means you can pretty much do what you want. :smile:

**Comment by drwpow** [comment]
Right after I wrote this, I ended up slapping something together using `yaml`’s AST. It’s probably not a perfect conversion, but it’s workable for my purposes: https://github.com/drwpow/yaml-to-momoa. Just published to the `yaml-to-momoa` package.

I spent about, oh, 30 minutes starting down building my own simple YAML parser, then when looking at the spec was reminded of all the silly things it allows. And so just reached for an existing _actual_ parser.

Feel free to incorporate any of this into Momoa if you’d like (or I can make a PR too), though my approach would add `yaml` as a dependency. Or it can be separate. You can also pretty much do what you want 😉. Cheers 🍻
