### ISSUE TITLE
parent node references

### ISSUE THREAD

**Issue by boneskull** [humanwhocodes/momoa#126]
Hi,

I'm curious if it makes sense for each `Node` to have a reference to its parent (e.g., a `parent` property). Because there's no such thing, it's onerous to walk back up to the root from any given `Node`. For example: if iterating over the tree, one would need to do something like the following to maintain the reference:

```ts
const parents = new WeakMap<Node, Node>;
for (const {node, parent} of iterate(root)) {
  if (parent) {
    parents.set(node, parent);
  }
  // later
  while (parent) {
    node = parent;
    parent = parents.get(node);
  }
  const root = node;
}
```

Would adding a `parent` reference to each `Node` be considered an anti-pattern?  I don't know anything about designing AST data structures.

**Comment by nzakas** [comment]
Parsers generally don't create references to parent nodes in the produce AST. That typically is done by an application that is consuming the AST. (ESLint adds a `.parent` node to the ESTree AST for convenience, but honestly, I'm avoiding doing that with other languages now as it creates challenges related to duplication and serialization of nodes.)

**Comment by boneskull** [comment]
thanks for the explanation
