### ISSUE TITLE
Dangling commas in JSONC

### ISSUE THREAD

**Issue by hildjj** [humanwhocodes/momoa#135]
**Tell us about your environment**

* **Momoa Version:**
3.2.2

* **Node Version:**
v22.9.0

* **npm Version:**
10.9.0

**Which function(s) is causing a problem?**

[ ] `interpret()`
[ ] `iterator()`
[ ] `parse()`
[x] `print()`
[ ] `traverse()`
[ ] `tokenize()`

**Example JSON code that demonstrates the problem:**

```jsonc
{
  "foo": 1,
}
```

**What did you do?**

```js
parse('{"foo": 1,}', {mode: "jsonc"})
```

**What did you expect to happen?**

```js
{
  type: 'Document',
  body: {
    type: 'Object',
    members: [
      {
        type: 'Member',
        name: {
          type: 'String',
          value: 'foo',
          loc: {
            start: { line: 1, column: 2, offset: 1 },
            end: { line: 1, column: 7, offset: 6 }
          }
        },
        value: {
          type: 'Number',
          value: 1,
          loc: {
            start: { line: 1, column: 9, offset: 8 },
            end: { line: 1, column: 10, offset: 9 }
          }
        },
        loc: {
          start: { line: 1, column: 2, offset: 1 },
          end: { line: 1, column: 10, offset: 9 }
        }
      }
    ],
    loc: {
      start: { line: 1, column: 1, offset: 0 },
      end: { line: 1, column: 11, offset: 10 }
    }
  },
  loc: {
    start: { line: 1, column: 1, offset: 0 },
    end: { line: 1, column: 11, offset: 10 }
  }
}
```

(with end positions slightly different.  I just parsed without the trailing comma.)

**What actually happened?**

```
Uncaught:
UnexpectedToken [Error]: Unexpected token RBrace found. (1:11)
    at assertTokenType (file:///Users/hildjj/track/@eslint/json/node_modules/.pnpm/@humanwhocodes+momoa@3.2.2/node_modules/@humanwhocodes/momoa/dist/momoa.js:1716:19)
    at parseProperty (file:///Users/hildjj/track/@eslint/json/node_modules/.pnpm/@humanwhocodes+momoa@3.2.2/node_modules/@humanwhocodes/momoa/dist/momoa.js:1855:13)
    at parseObject (file:///Users/hildjj/track/@eslint/json/node_modules/.pnpm/@humanwhocodes+momoa@3.2.2/node_modules/@humanwhocodes/momoa/dist/momoa.js:1918:30)
    at parseValue (file:///Users/hildjj/track/@eslint/json/node_modules/.pnpm/@humanwhocodes+momoa@3.2.2/node_modules/@humanwhocodes/momoa/dist/momoa.js:2063:24)
    at Module.parse (file:///Users/hildjj/track/@eslint/json/node_modules/.pnpm/@humanwhocodes+momoa@3.2.2/node_modules/@humanwhocodes/momoa/dist/momoa.js:2075:21) {
  line: 1,
  column: 11,
  offset: 10
}
```

**What do you think the solution is?**

JSONC doesn't have a formal definition that I could find, but the one that [@eslint/json](https://github.com/eslint/json) points to is [Microsoft's implementation](https://github.com/Microsoft/node-jsonc-parser).  Both typescript and vscode accept trailing commas in their config files, so I believe `allowTrailingComma` should at least be an option for jsonc mode.

**Comment by hildjj** [comment]
Are you likely to want to make it an option, or just always accept trailing commas?  I'd prefer always-accept, or for the option to default to always-accept, so that I don't have to ask @eslint/json for extra work.  I would understand the opposite preference, however.

**Comment by nzakas** [comment]
I think always on is the right choice as that is probably what most people expect.

**Comment by nzakas** [comment]
Actually, it looks like the default is to not allow trailing commas. 🤔 
https://github.com/microsoft/node-jsonc-parser/blob/3c9b4203d663061d87d4d34dd0004690aef94db5/src/impl/parser.ts#L22

I tested this in VS Code by switching a normal JSON file to JSONC and it flagged the trailing comma as a problem. 

So, I think I should match that behavior and have an option that is disabled by default.
