### ISSUE TITLE
Trailling comma should not be allowed

### ISSUE THREAD

**Issue by francisfeng** [humanwhocodes/momoa#14]
**Tell us about your environment**

* **Momoa Version:** 2.0.1
* **Node Version:** 15.2.0
* **npm Version:** 7.13.0

**Which function(s) is causing a problem?**

[ ] `interpret()`
[ ] `iterator()`
[x] `parse()`
[ ] `print()`
[ ] `traverse()`
[ ] `tokenize()`

**Example JSON code that demonstrates the problem:**

```json
{
   "key1": [true, false, null],
}
```

**What did you do?**
```js
const { parse } = require('@humanwhocodes/momoa');

const ast = parse("{\"a\": \"hello world\",}");
console.log(ast)
```

There is also an online demo: [AST explorer](https://astexplorer.net/#/gist/ad5b75044f5a3acf5237ce1884d49b92/496fc7fc8bd3a96a60613afc9b311b7cbfe42ee9)

**What did you expect to happen?**
The parser should throw an error.

**What actually happened?**
It successfully parsed the JSON string.

**What do you think the solution is?**

**Comment by nzakas** [comment]
Thanks. Definitely looks like a bug.
