### ISSUE TITLE
When parsing a hexadecimal in JSON5 mode the value becomes NaN

### ISSUE THREAD

**Issue by ota-meshi** [humanwhocodes/momoa#151]
**Tell us about your environment**

* **Momoa Version**: 3.3.1
* **Node Version**: v20.17.0
* **npm Version**: 10.8.2

**Which function(s) is causing a problem?**

[ ] `interpret()`
[ ] `iterator()`
[x] `parse()`
[ ] `print()`
[ ] `traverse()`
[ ] `tokenize()`

**Example JSON code that demonstrates the problem:**

```json5
-0x123
```

**What did you do?**

I used Momoa to parse the code as JSON5.

**What did you expect to happen?**

A Number node with a `value` of `-291` is generated.

**What actually happened?**

A Number node with a `value` of `NaN` is generated.

**What do you think the solution is?**

For JSON5 mode, I think additional logic is required.

https://github.com/humanwhocodes/momoa/blob/22b4e6ed23546de511cf5bcdf45625e1ca2abd4b/js/src/parse.js#L163

**Comment by nzakas** [comment]
Thanks, I'll take a look.
