### ISSUE TITLE
Unescape json5 keys that aren't in quotes

### ISSUE THREAD

**Issue by hildjj** [humanwhocodes/momoa#164]
**Tell us about your environment**

* **Momoa Version:** 3.3.3
* **Node Version:** v23.3.0
* **npm Version:** 10.9.1

**Which function(s) is causing a problem?**

[ ] `interpret()`
[ ] `iterator()`
[x] `parse()`
[ ] `print()`
[ ] `traverse()`
[ ] `tokenize()`

**Example JSON code that demonstrates the problem:**

```json5
{f\\u006fo: true}
```

**What did you do?**

const result = parse('{f\\u006fo: true}', {mode: 'json5'})

**What did you expect to happen?**

result.body.members[0].name.name === 'foo'

**What actually happened?**

result.body.members[0].name.name === 'f\\u006fo'

**What do you think the solution is?**

Unescape escape sequences for unquoted object keys, when in JSON5 mode.  The json5 package does this unescaping, and unescaping currently takes place when the key is quoted.

**Comment by nzakas** [comment]
Thanks yeah, definitely a bug. I'll take a look.
