### ISSUE TITLE
Dangling commas in arrays should produce an error

### ISSUE THREAD

**Issue by tmcw** [humanwhocodes/momoa#19]
**Tell us about your environment**

* **Momoa Version:** 2.0.2
* **Node Version:** 16.13.1
* **npm Version:** 6.14.15

**Which function(s) is causing a problem?**

[ ] `interpret()`
[ ] `iterator()`
[x] `parse()`
[ ] `print()`
[ ] `traverse()`
[ ] `tokenize()`

**Example JSON code that demonstrates the problem:**

```json
[1,]
```

**What did you do?**

This input parses with momoa, but does not parse in JSON. Trailing commas in objects were fixed in #14 but not fixed in the array case.

**What did you expect to happen?**

This should produce an error.

**What actually happened?**

This input is parsed.

**What do you think the solution is?**

This should produce a syntax error.

**Comment by nzakas** [comment]
Oops thanks. Looks like the same problem that I had with objects initially: https://github.com/humanwhocodes/momoa/issues/14

**Comment by tmcw** [comment]
Sorry, not to prod - looks like 2.0.3 is tagged but not pushed to npm yet?

**Comment by nzakas** [comment]
Hmmm, it looks like the automated publish to npm failed. Not sure what happened there. I’ll take a look tomorrow.
