### ISSUE TITLE
Moma accepts numbers in engineering notation with e but without exponent

### ISSUE THREAD

**Issue by brennie** [humanwhocodes/momoa#21]
**Tell us about your environment**

* **Momoa Version:** 2.0.3
* **Node Version:** 16.14.2
* **npm Version:** 8.5.0

**Which function(s) is causing a problem?**

[ ] `interpret()`
[ ] `iterator()`
[x] `parse()`
[ ] `print()`
[ ] `traverse()`
[ ] `tokenize()`

**Example JSON code that demonstrates the problem:**

```json
4e
```

**What did you do?**

```js
~/W/t/momoa-test> node
Welcome to Node.js v16.14.2.
Type ".help" for more information.
> const momoa = require("@humanwhocodes/momoa");
undefined
> momoa.parse("4e")
{
  type: 'Document',
  body: {
    type: 'Number',
    value: NaN,
    loc: { start: [Object], end: [Object] }
  },
  loc: {
    start: { line: 1, column: 1, offset: 0 },
    end: { line: 1, column: 3, offset: 2 }
  }
}
```

**What did you expect to happen?**

When using JSON.parse
```js
~/W/t/momoa-test> node
Welcome to Node.js v16.14.2.
Type ".help" for more information.
> JSON.parse("4e")
Uncaught SyntaxError: Unexpected end of JSON input
```

**What actually happened?**

Momoa accepts `4e` and parses it as `NaN` when it should fail to parse.

**What do you think the solution is?**

**Comment by nzakas** [comment]
Hmm, that’s not good. Looks like an oversight in this general area:
https://github.com/humanwhocodes/momoa/blob/f7d5a3fcad186eb8d1f88b0786b3b27251b801a3/src/tokens.js#L242
