### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by sbmsr** [humanwhocodes/momoa#41]
Would you consider accepting a PR that provides typescript support? If so, I'd be interested in helping contribute this.

**Comment by nzakas** [comment]
I don’t want to rewrite in TypeScript. Is that what you’re asking?

**Comment by sbmsr** [comment]
No, I am proposing I add types without converting the code to TypeScript. [This SO answer shows how it is done](https://stackoverflow.com/a/53710641).

I would be willing to do this, but only if you are open to merging it into the codebase.

**Comment by nzakas** [comment]
Ah I see. I’m open to it. I’ve have been using JSDoc to generate type definitions files in some of my other projects like this one:

https://github.com/humanwhocodes/env

I prefer JSDoc definitions to .d.ts files, but otherwise, I’d be happy to accept such a contribution.
