### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by ANU8151** [humanwhocodes/momoa#5]
**Tell us about your environment**

* **Momoa Version: 1.0**
* **Node Version: 15.3.0**
* **npm Version: 7.0.14**

**Which function(s) is causing a problem?**
[ ] `parse()`

**Example JSON code that demonstrates the problem:**

```
{
    "models" : {
      "Post":{
        "id":true,
        "title" : "string:400",
        "content" : "longtext",
        "published_at" : "nullable timestamp",
          "relationships":{
          "hasMany" : "Comment",
          "belongsToMany": "Media, Site"
        }
      }
    },
    "controllers" : {
      "Post":{
        "index": {
          "query": "all",
          "render": "post.index with:posts"
        },
        "store":{
          "validate" : "title, content",
          "save": "post",
          "send": "ReviewNotification to:post.author with:post",
          "dispatch": "SyncMedia with:post",
          "fire": "NewPost with:post",
          "flash": "post.title",
          "redirect": "post.index",
        } 
      }
    }
  }

```

**What did you do?**

**What did you expect to happen?**

**What actually happened?**
![Screenshot 2020-11-30 000532](https://user-images.githubusercontent.com/26343845/100552826-06331080-32a3-11eb-899a-93910f0f977d.png)
![Screenshot 2020-11-30 001555](https://user-images.githubusercontent.com/26343845/100552827-07643d80-32a3-11eb-99d9-07c644464ab3.png)

**Comment by mati-o** [comment]
The function expects a `string`, but you are passing an `Object`, you can use `JSON.stringify(YamlData, null, 2)` to make it work. The `null, 2` are to preserve the whitespaces and lines, can be omitted if you don't need it
