### ISSUE TITLE
Line endings are inconsistent during normalize

### ISSUE THREAD

**Issue by mati-o** [humanwhocodes/momoa#6]
* **Windows 10**

* **Momoa Version: 1.0.0**
* **Node Version: 13.0.1**
* **npm Version: 6.12.0**

**Which function(s) is causing a problem?**

[ ] `interpret()`
[ ] `iterator()`
[ ] `parse()`
[ ] `print()`
[ ] `traverse()`
[x] `tokenize()`

I have a bunch of JSON files supplied by my users with `\r\n` as line endings. Some of them have empty lines (like `\r\n\r\n`) which messes up the offset of the token by shifting it by one for each empty line.

**Reproduction**:

To illustrate the problem, I'll simply focus on the regex that happens on the beginning:

```js
let text = '\r\n\r\n\r\n';
text = text.replace(/\n\r?/g, "\n");
``` 

**Expected**:
`text` to be `\n\n\n`

**Actual**:
`text` was `\r\n\n\n`;

**Possible solution**:
Change regex to `/\r\n?/g`.

**More cases**
`{\r\n  "a": 1,\r\n\r\n"b": 2\r\n\r\n}` which yields
`{\r\n  "a": 1,\r\n\n"b": 2\r\n\n}`

~~## Feature Request~~

~~Beside of the aforementioned problem, I have a feature request - provide an options parameter that will disable the line ending normalization and keep the originals.~~

~~The reason is that I am having these files and printing them to the console, highlighting specific tokens, so I have to track the original chars.~~

~~The current situation forces me to skip `\r` manually. Also with the problem, my current workaround is to do the same text replacement on my content.~~

**EDIT**: Opened a separate Feature Request #7 

I'll be glad to send a PR once we agree on a solution. Let me know if any more clarifications required. Cool library btw(!)

Regards

**Comment by nzakas** [comment]
That does look like a bug, thanks for reporting it. 

Please open a separate issue for a feature request so we can discuss separately.

**Comment by nzakas** [comment]
Can you give me an example JSON string that is causing you problems, the actual output you're getting, and the what you expected to be different?

I'm not seeing any difference in the returned data with the change you suggested, so I need a solid example to work with. Thanks.

**Comment by mati-o** [comment]
Sure, attached below is a textfile (since GitHub prohibits `json` extension :open_mouth: ). Also, I have attached a sample code, which I hope won't confuse, which does the following:

1. Parses the JSON with tokens and ranges
2. Iterates over each character and printing them one by one, adding an excalmation mark `!` when entering a token of type string. 

Simply, it just re-print the JSON but with whitespace preservation (In my original case, I add custom colors to the output to highlight tokens).

**All line-endings are CRLF**
[bad.txt](https://github.com/humanwhocodes/momoa/files/5764771/bad.txt)

This is the content of `bad.txt`:
```json
{
  "a":1,
  "b":2,


  "c":3,

  "d":4,

  
  "e":5
}
```
### Sample code
```javascript

const fs = require('fs');
const { parse } = require('@humanwhocodes/momoa');

// Load the file contents
const testJson = fs.readFileSync('bad.json', 'utf-8');

// Get the tokens and range
const { tokens } = parse(testJson, { tokens: true, ranges: true });

// I keep two pointers while looping over all characters:
// i - for the current character to print, 
// currentTokenIdx - which token is currently being printed
for (let i = 0, currentTokenIdx = 0; i < testJson.length; ++i) {

  // Get current token
  const currentToken = tokens[currentTokenIdx];

  if (currentToken) {
    if (i === currentToken.range[1]) {
      // Advance to next token when we reach the end of the current
      currentTokenIdx++;
    }

    // For tokens of type string, I just prepend them with an exclamation mark
    if (currentToken.range[0] === i && currentToken.type === 'String') {
      fs.writeFileSync(1, '!');
    }
  }

  fs.writeFileSync(1, testJson[i]);
}
```

### Expected Result
```txt
{
  !"a":1,
  !"b":2,


  !"c":3,

  !"d":4,

  
  !"e":5
}
```
Expected to see an exclamation mark right before the start of each key

### Actual Result
```txt
{
  !"a":1,
  !"b":2,


!  "c":3,
!
  "d":4,

  !
  "e":5
}
```
Actually, each continuous line-break with CR-LF causes a shift by one in the range from the original value.

Let me know I can assist somehow more

**Comment by nzakas** [comment]
Sorry, I’m not sure how to interpret the results you shared. What I’m looking for is a minimal test case with the resulting tokens and what you think are wrong with those tokens.

**Comment by mati-o** [comment]
Okay, I'll try to simplify and improve around next week hopefully

**Comment by nzakas** [comment]
Sound good!

In the meantime, I discovered something: changing the regex pattern used during the normalization doesn't result in different token ranges because there is another part of the code that looks for `\r` separately from `\n`.

Ultimately, I can't remember why I did this normalization as it seems unnecessary. Need to dig in a bit more. I may just remove it in the next version.

**Comment by nzakas** [comment]
Finally dug into this and figured out what it should be doing and how to test it. See #8.
