### ISSUE TITLE
Stand alone browser version?

### ISSUE THREAD

**Issue by pkrumins** [humanwhocodes/momoa#62]
Thanks for creating this library!

I'm wondering if there's a stand alone browser version available that I can include via a `<script>` tag and start using it? 

Thank you!

**Comment by nzakas** [comment]
There are several ways you can do this:

1. Install Momoa via npm, and grab the `dist/momoa.js` file to deploy on your own.
2. Use Skypack such as:

```js
import { parse } from "https://cdn.skypack.dev/@humanwhocodes/momoa";
```

You can't put the URL directly into a `<script>` tag because it's an ESM file that you need call via `import`.

I'll add this into the README.
