### ISSUE TITLE
Feature Request: allow controlling line-ending normalization using `options`

### ISSUE THREAD

**Issue by mati-o** [humanwhocodes/momoa#7]
* **Momoa Version:** 1.0.0
* **Node Version:** 13.0.1
* **npm Version:** 6.12.0
* **OS:** Windows 10

**Which function(s) is causing a problem?**

[ ] `interpret()`
[ ] `iterator()`
[x] `parse()`
[ ] `print()`
[ ] `traverse()`
[x] `tokenize()`

Current behavior is that `parse` and `tokenize` will replace line endings to `\n`. I would like to keep original line-endings to match the `ranges` correctly. I am printing the JSON using a custom syntax highlighter, therefore I'd like to match the index of each token with the original document.

Related to #6

### Proposed Solution
```diff
const { tokens } = parse(testJson, { 
  tokens: true, 
  ranges: true, 
+ keepLineEndings: true
});
``

**Comment by nzakas** [comment]
I wonder if there's any value to keeping line-ending normalization as a feature at all. I can't remember why I included it (probably to make parsing easier) but it seems much more desirable to always keep the original line endings.

So, I'm not opposed to adding a new option, I just wonder if there's any reason to even provide the ability to normalize line endings or if I should just remove that altogether.

**Comment by mati-o** [comment]
The only reason I suggested adding the option is to keep backward compatibility with current library users without introducing a major semver bump. Thank you very much
